version: 2
updates:
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "daily"
      target-branch: "master"
      assignees:
          - "OmerBilgin21"
      ignore:
          - dependency-name: "pymongo"
          - dependency-name: "motor"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
