[tool.ruff]
exclude = [".git", ".ruff_cache", ".venv", "venv", "~/"]
target-version = "py310"

line-length = 88
indent-width = 4

[tool.ruff.lint]
select = ["ALL"]

ignore = [
    "ANN401",
    "T201",
    "B008",
    "UP032",
    "D100",
    "D206",
    "D400",
    "D401",
    "D406",
    "D413",
    "ERA001",
    "D104",
    "D415",
    "D407",
    "G001",
    "D203",
    "D212",
    "D203",
    "D213",
    "FIX004",
    "TD003",
    "PLR0913",
    "D101",
    "N815",
    "S104",
    "W191",
]

fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"

indent-style = "tab"

skip-magic-trailing-comma = false

line-ending = "auto"
